apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "root"
            - name: MARIADB_DATABASE
              value: "Blogs"
          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-server
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mariadb
